name: Educa
options:
  bundleIdPrefix: com.educa
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    INFOPLIST_FILE: "Sources/Info.plist"
    CODE_SIGN_STYLE: "Automatic"
    PRODUCT_BUNDLE_IDENTIFIER: "com.educa.app"

targets:
  Educa:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
      - path: Resources
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: "Sources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "com.educa.app"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: "Educa"
        CFBundleDisplayName: "Educa"
        CFBundleIdentifier: "com.educa.app"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  EducaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Educa

  EducaUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: Educa

schemes:
  Educa:
    build:
      targets:
        Educa: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - EducaTests
        - EducaUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

