name: NPLearn
options:
  deploymentTarget:
    iOS: 16.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.19.0
targets:
  NPLearn:
    type: application
    platform: iOS
    sources:
      - path: Sources
        includes:
          - "**/*.swift"
        excludes:
          - "main.swift"
      - path: GoogleService-Info.plist
        type: file
        buildPhase: resources
      # Legacy learning data (for backwards compatibility)
      - path: nepali_learning_data.json
        type: file
        buildPhase: resources
      # New data-driven JSON resources
      - path: Resources/manifest.json
        type: file
        buildPhase: resources
      - path: Resources/vocabulary.json
        type: file
        buildPhase: resources
      - path: Resources/grammar.json
        type: file
        buildPhase: resources
      - path: Resources/practice.json
        type: file
        buildPhase: resources
      - path: Resources/reading.json
        type: file
        buildPhase: resources
      - path: Resources/games.json
        type: file
        buildPhase: resources
      # Speaking and Writing data
      - path: Resources/speaking.json
        type: file
        buildPhase: resources
      - path: Resources/writing.json
        type: file
        buildPhase: resources
      # Level-specific learning data
      - path: Resources/nepali_learning_data_beginner.json
        type: file
        buildPhase: resources
      - path: Resources/nepali_learning_data_elementary.json
        type: file
        buildPhase: resources
      - path: Resources/nepali_learning_data_intermediate.json
        type: file
        buildPhase: resources
      - path: Resources/nepali_learning_data_advanced.json
        type: file
        buildPhase: resources
      - path: Resources/nepali_learning_data_proficient.json
        type: file
        buildPhase: resources
      - path: Sources/Assets.xcassets
        type: folder.assetcatalog
        buildPhase: resources
      - path: Sources/NPLearn.entitlements
        type: file
        buildPhase: none
    settings:
      base:
        PRODUCT_NAME: NPLearn
        PRODUCT_BUNDLE_IDENTIFIER: com.company.nplearn
        CURRENT_PROJECT_VERSION: '3'
        MARKETING_VERSION: '1.1'
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: 9A3YFRQ7SM
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Sources/NPLearn.entitlements
        DWARF_DSYM_FOLDER_PATH: $(CONFIGURATION_BUILD_DIR)
        DWARF_DSYM_FILE_NAME: $(EXECUTABLE_NAME).dSYM
        STRIP_STYLE: non-global
        STRIPFLAGS: -x
        ENABLE_BITCODE: NO
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf
          COPY_PHASE_STRIP: NO
          STRIP_INSTALLED_PRODUCT: NO
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          COPY_PHASE_STRIP: NO
          STRIP_INSTALLED_PRODUCT: YES
    info:
      path: Sources/Info.plist
      properties:
        CFBundleIconName: AppIcon
        CFBundleIdentifier: com.company.nplearn
        CFBundleName: NPLearn
        CFBundleShortVersionString: '1.1'
        CFBundleVersion: '3'
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: NPLearn needs access to your microphone for speaking practice exercises.
        NSPhotoLibraryUsageDescription: NPLearn needs access to your photo library to save learning materials.
        NSPhotoLibraryAddUsageDescription: NPLearn needs permission to save photos to your library.
        NSCameraUsageDescription: NPLearn needs access to your camera for practice exercises.
        NSSpeechRecognitionUsageDescription: NPLearn needs speech recognition to evaluate your pronunciation.
    scheme:
      testTargets:
        - name: NPLearnTests
        - name: NPLearnUITests
    dependencies:
      - package: Firebase
        products:
          - FirebaseAuth
  NPLearnTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: NPLearn
  NPLearnUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: NPLearn
