# =====================================================
# SpiceBite - iOS App Project Configuration
# =====================================================
# 
# Indian & Nepali Restaurant Comparison App (Worldwide)
#
# BEFORE APP STORE SUBMISSION:
# 1. Set DEVELOPMENT_TEAM to your Apple Developer Team ID
# 2. Update PRODUCT_BUNDLE_IDENTIFIER if needed
# 3. Increment MARKETING_VERSION for each release
# 4. Increment CURRENT_PROJECT_VERSION for each build
# =====================================================

name: SpiceBite
options:
  bundleIdPrefix: com.company
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    # ⚠️ REQUIRED: Set your Apple Developer Team ID
    DEVELOPMENT_TEAM: ""
    
    # App Version
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    
    # Swift and iOS versions
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    
    # App configuration
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    INFOPLIST_FILE: "Sources/Info.plist"
    CODE_SIGN_STYLE: "Automatic"
    PRODUCT_BUNDLE_IDENTIFIER: "com.company.spicebite"
    
    # Optimization settings
    SWIFT_OPTIMIZATION_LEVEL: "-O"
    GCC_OPTIMIZATION_LEVEL: "s"
    ENABLE_BITCODE: "NO"
    ENABLE_ATS: "YES"

targets:
  SpiceBite:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
      - path: Resources
        excludes:
          - "**/.DS_Store"
    settings:
      INFOPLIST_FILE: "Sources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "com.company.spicebite"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: "SpiceBite"
        CFBundleDisplayName: "SpiceBite"
        CFBundleIdentifier: "com.company.spicebite"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false

  SpiceBiteTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: SpiceBite

schemes:
  SpiceBite:
    build:
      targets:
        SpiceBite: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SpiceBiteTests
    archive:
      config: Release
      revealArchiveInOrganizer: true
