name: JLearn
options:
  deploymentTarget:
    iOS: 16.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.19.0
targets:
  JLearn:
    type: application
    platform: iOS
    sources:
      - path: Sources
        includes:
          - "**/*.swift"
        excludes:
          - "main.swift"
      - path: GoogleService-Info.plist
        type: file
        buildPhase: resources
      - path: Resources/japanese_learning_data_n5_jisho.json
        type: file
        buildPhase: resources
      - path: Resources/japanese_learning_data_n4_jisho.json
        type: file
        buildPhase: resources
      - path: Resources/japanese_learning_data_n3_jisho.json
        type: file
        buildPhase: resources
      - path: Resources/japanese_learning_data_n2_jisho.json
        type: file
        buildPhase: resources
      - path: Resources/japanese_learning_data_n1_jisho.json
        type: file
        buildPhase: resources
      - path: Sources/Assets.xcassets
        type: folder.assetcatalog
        buildPhase: resources
      - path: Sources/JLearn.entitlements
        type: file
        buildPhase: none
    settings:
      base:
        PRODUCT_NAME: JLearn
        PRODUCT_BUNDLE_IDENTIFIER: com.company.jplearning
        CURRENT_PROJECT_VERSION: '3'
        MARKETING_VERSION: '1.2'
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: 9A3YFRQ7SM
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Sources/JLearn.entitlements
        DWARF_DSYM_FOLDER_PATH: $(CONFIGURATION_BUILD_DIR)
        DWARF_DSYM_FILE_NAME: $(EXECUTABLE_NAME).dSYM
        STRIP_STYLE: non-global
        STRIPFLAGS: -x
        ENABLE_BITCODE: NO
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf
          COPY_PHASE_STRIP: NO
          STRIP_INSTALLED_PRODUCT: NO
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          COPY_PHASE_STRIP: NO
          STRIP_INSTALLED_PRODUCT: YES
    info:
      path: Sources/Info.plist
      properties:
        CFBundleIconName: AppIcon
        CFBundleIdentifier: com.company.jplearning
        CFBundleName: JLearn
        CFBundleShortVersionString: '1.2'
        CFBundleVersion: '3'
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: JLearn needs access to your microphone for speaking practice exercises.
        NSPhotoLibraryUsageDescription: JLearn needs access to your photo library to save learning materials.
        NSPhotoLibraryAddUsageDescription: JLearn needs permission to save photos to your library.
        NSCameraUsageDescription: JLearn needs access to your camera for practice exercises.
        NSSpeechRecognitionUsageDescription: JLearn needs speech recognition to evaluate your pronunciation.
    scheme:
      testTargets:
        - name: JLearnTests
        - name: JLearnUITests
    dependencies:
      - package: Firebase
        products:
          - FirebaseAuth
  JLearnTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: JLearn
  JLearnUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: JLearn

