#!/usr/bin/env python3
"""
Flashcard Generator for NPLearn
================================
Generates 100+ flashcards per level across multiple categories
"""

import json
from pathlib import Path
from config import RESOURCES_DIR, VERSION, LEVELS

# ═══════════════════════════════════════════════════════════════════════════════
# COMPREHENSIVE NEPALI VOCABULARY DATABASE
# ═══════════════════════════════════════════════════════════════════════════════

BEGINNER_VOCAB = {
    "greetings": [
        ("नमस्ते", "Hello", "namaste", "Traditional greeting"),
        ("धन्यवाद", "Thank you", "dhanyabad", "Gratitude"),
        ("माफ गर्नुहोस्", "Sorry/Excuse me", "maaf garnuhos", "Apology"),
        ("कृपया", "Please", "kripaya", "Polite request"),
        ("स्वागतम्", "Welcome", "swagatam", "Welcoming"),
        ("शुभ प्रभात", "Good morning", "shubha prabhat", "Morning greeting"),
        ("शुभ रात्रि", "Good night", "shubha ratri", "Night greeting"),
        ("फेरि भेटौंला", "See you again", "pheri bhetaula", "Farewell"),
        ("कस्तो छ?", "How are you?", "kasto chha?", "Wellbeing inquiry"),
        ("ठीक छ", "I'm fine", "thik chha", "Response"),
        ("शुभ दिन", "Good day", "shubha din", "Day greeting"),
        ("शुभ साँझ", "Good evening", "shubha sanjh", "Evening greeting"),
        ("बिदा", "Goodbye", "bida", "Farewell"),
        ("हजुर", "Yes (polite)", "hajur", "Polite affirmative"),
        ("होइन", "No", "hoina", "Negative"),
    ],
    "numbers": [
        ("एक", "One (1)", "ek", "Number 1"),
        ("दुई", "Two (2)", "dui", "Number 2"),
        ("तीन", "Three (3)", "tin", "Number 3"),
        ("चार", "Four (4)", "char", "Number 4"),
        ("पाँच", "Five (5)", "panch", "Number 5"),
        ("छ", "Six (6)", "chha", "Number 6"),
        ("सात", "Seven (7)", "saat", "Number 7"),
        ("आठ", "Eight (8)", "aath", "Number 8"),
        ("नौ", "Nine (9)", "nau", "Number 9"),
        ("दश", "Ten (10)", "das", "Number 10"),
        ("एघार", "Eleven (11)", "eghaara", "Number 11"),
        ("बाह्र", "Twelve (12)", "bahra", "Number 12"),
        ("तेह्र", "Thirteen (13)", "tehra", "Number 13"),
        ("चौध", "Fourteen (14)", "chaudha", "Number 14"),
        ("पन्ध्र", "Fifteen (15)", "pandhra", "Number 15"),
        ("सोह्र", "Sixteen (16)", "sohra", "Number 16"),
        ("सत्र", "Seventeen (17)", "satra", "Number 17"),
        ("अठार", "Eighteen (18)", "athara", "Number 18"),
        ("उन्नाइस", "Nineteen (19)", "unnais", "Number 19"),
        ("बीस", "Twenty (20)", "bis", "Number 20"),
        ("तीस", "Thirty (30)", "tis", "Number 30"),
        ("चालीस", "Forty (40)", "chalis", "Number 40"),
        ("पचास", "Fifty (50)", "pachas", "Number 50"),
        ("साठी", "Sixty (60)", "sathi", "Number 60"),
        ("सत्तरी", "Seventy (70)", "sattari", "Number 70"),
        ("असी", "Eighty (80)", "asi", "Number 80"),
        ("नब्बे", "Ninety (90)", "nabbe", "Number 90"),
        ("सय", "Hundred (100)", "saya", "Number 100"),
        ("हजार", "Thousand (1000)", "hajar", "Number 1000"),
        ("लाख", "Hundred thousand", "lakh", "100,000"),
    ],
    "family": [
        ("बुबा", "Father", "buba", "Father"),
        ("आमा", "Mother", "aama", "Mother"),
        ("दाजु", "Elder brother", "daju", "Elder brother"),
        ("भाइ", "Younger brother", "bhai", "Younger brother"),
        ("दिदी", "Elder sister", "didi", "Elder sister"),
        ("बहिनी", "Younger sister", "bahini", "Younger sister"),
        ("परिवार", "Family", "pariwar", "Family"),
        ("हजुरबुवा", "Grandfather", "hajurbuwa", "Grandfather"),
        ("हजुरआमा", "Grandmother", "hajuraama", "Grandmother"),
        ("छोरा", "Son", "chhora", "Son"),
        ("छोरी", "Daughter", "chhori", "Daughter"),
        ("श्रीमान", "Husband", "shriman", "Husband"),
        ("श्रीमती", "Wife", "shrimati", "Wife"),
        ("काका", "Uncle (paternal)", "kaka", "Father's brother"),
        ("काकी", "Aunt (paternal)", "kaki", "Father's brother's wife"),
        ("मामा", "Uncle (maternal)", "mama", "Mother's brother"),
        ("माइजू", "Aunt (maternal)", "maiju", "Mother's brother's wife"),
        ("नाति", "Grandson", "naati", "Grandson"),
        ("नातिनी", "Granddaughter", "naatini", "Granddaughter"),
        ("साथी", "Friend", "saathi", "Friend"),
    ],
    "colors": [
        ("रातो", "Red", "rato", "Red color"),
        ("निलो", "Blue", "nilo", "Blue color"),
        ("हरियो", "Green", "hariyo", "Green color"),
        ("पहेंलो", "Yellow", "pahelo", "Yellow color"),
        ("सेतो", "White", "seto", "White color"),
        ("कालो", "Black", "kalo", "Black color"),
        ("सुन्तला रङ", "Orange", "suntala rang", "Orange color"),
        ("गुलाबी", "Pink", "gulabi", "Pink color"),
        ("खैरो", "Brown", "khairo", "Brown color"),
        ("बैजनी", "Purple", "baijani", "Purple color"),
        ("खरानी", "Gray", "kharani", "Gray color"),
        ("सुनौलो", "Golden", "sunaulo", "Golden color"),
        ("रूपाली", "Silver", "rupali", "Silver color"),
        ("आकाशे", "Sky blue", "akashe", "Light blue"),
        ("मरुन", "Maroon", "marun", "Maroon color"),
    ],
    "days": [
        ("आइतबार", "Sunday", "aitabar", "First day"),
        ("सोमबार", "Monday", "sombar", "Second day"),
        ("मंगलबार", "Tuesday", "mangalbar", "Third day"),
        ("बुधबार", "Wednesday", "budhabar", "Fourth day"),
        ("बिहिबार", "Thursday", "bihibar", "Fifth day"),
        ("शुक्रबार", "Friday", "shukrabar", "Sixth day"),
        ("शनिबार", "Saturday", "sanibar", "Holiday in Nepal"),
    ],
    "food": [
        ("खाना", "Food/Meal", "khana", "Food"),
        ("पानी", "Water", "pani", "Water"),
        ("भात", "Rice (cooked)", "bhaat", "Cooked rice"),
        ("दाल", "Lentils", "daal", "Lentil soup"),
        ("चिया", "Tea", "chiya", "Tea"),
        ("दूध", "Milk", "dudh", "Milk"),
        ("रोटी", "Bread", "roti", "Flatbread"),
        ("तरकारी", "Vegetables", "tarkari", "Vegetable dish"),
        ("मासु", "Meat", "maasu", "Meat"),
        ("स्याउ", "Apple", "syau", "Apple"),
        ("केरा", "Banana", "kera", "Banana"),
        ("अण्डा", "Egg", "anda", "Egg"),
        ("आलु", "Potato", "aalu", "Potato"),
        ("गोलभेडा", "Tomato", "golbheda", "Tomato"),
        ("प्याज", "Onion", "pyaj", "Onion"),
        ("लसुन", "Garlic", "lasun", "Garlic"),
        ("अदुवा", "Ginger", "aduwa", "Ginger"),
        ("नुन", "Salt", "nun", "Salt"),
        ("चिनी", "Sugar", "chini", "Sugar"),
        ("तेल", "Oil", "tel", "Cooking oil"),
        ("घिउ", "Ghee", "ghiu", "Clarified butter"),
        ("दही", "Yogurt", "dahi", "Yogurt"),
        ("सुन्तला", "Orange", "suntala", "Orange fruit"),
        ("आँप", "Mango", "aap", "Mango"),
        ("अंगुर", "Grapes", "angur", "Grapes"),
    ],
    "body": [
        ("टाउको", "Head", "tauko", "Head"),
        ("आँखा", "Eye", "aankha", "Eye"),
        ("नाक", "Nose", "naak", "Nose"),
        ("कान", "Ear", "kaan", "Ear"),
        ("मुख", "Mouth/Face", "mukh", "Mouth"),
        ("हात", "Hand", "haat", "Hand"),
        ("खुट्टा", "Leg/Foot", "khutta", "Leg"),
        ("दाँत", "Teeth", "daat", "Teeth"),
        ("जिब्रो", "Tongue", "jibro", "Tongue"),
        ("कपाल", "Hair", "kapal", "Hair"),
        ("छाती", "Chest", "chhati", "Chest"),
        ("पेट", "Stomach", "pet", "Stomach"),
        ("ढाड", "Back", "dhad", "Back"),
        ("औंला", "Finger", "aunla", "Finger"),
        ("घाँटी", "Neck", "ghanti", "Neck"),
        ("काँध", "Shoulder", "kadh", "Shoulder"),
        ("कुहिनो", "Elbow", "kuhino", "Elbow"),
        ("घुँडा", "Knee", "ghuda", "Knee"),
        ("नङ", "Nail", "nang", "Nail"),
        ("छाला", "Skin", "chhala", "Skin"),
    ],
    "verbs": [
        ("खानु", "To eat", "khanu", "Eating"),
        ("पिउनु", "To drink", "piunu", "Drinking"),
        ("जानु", "To go", "jaanu", "Going"),
        ("आउनु", "To come", "aaunu", "Coming"),
        ("गर्नु", "To do", "garnu", "Doing"),
        ("बोल्नु", "To speak", "bolnu", "Speaking"),
        ("सुन्नु", "To listen", "sunnu", "Listening"),
        ("हेर्नु", "To see", "hernu", "Seeing"),
        ("पढ्नु", "To read", "padhnu", "Reading"),
        ("लेख्नु", "To write", "lekhnu", "Writing"),
        ("बस्नु", "To sit/live", "basnu", "Sitting"),
        ("उठ्नु", "To wake up", "uthnu", "Waking"),
        ("सुत्नु", "To sleep", "sutnu", "Sleeping"),
        ("खेल्नु", "To play", "khelnu", "Playing"),
        ("किन्नु", "To buy", "kinnu", "Buying"),
        ("बेच्नु", "To sell", "bechnu", "Selling"),
        ("दिनु", "To give", "dinu", "Giving"),
        ("लिनु", "To take", "linu", "Taking"),
        ("धुनु", "To wash", "dhunu", "Washing"),
        ("पकाउनु", "To cook", "pakaunu", "Cooking"),
    ],
    "adjectives": [
        ("राम्रो", "Good/Nice", "ramro", "Good"),
        ("नराम्रो", "Bad", "naramro", "Bad"),
        ("ठूलो", "Big", "thulo", "Big"),
        ("सानो", "Small", "sano", "Small"),
        ("नयाँ", "New", "naya", "New"),
        ("पुरानो", "Old", "purano", "Old"),
        ("तातो", "Hot", "tato", "Hot"),
        ("चिसो", "Cold", "chiso", "Cold"),
        ("मिठो", "Delicious", "mitho", "Delicious"),
        ("महँगो", "Expensive", "mahango", "Expensive"),
        ("सस्तो", "Cheap", "sasto", "Cheap"),
        ("लामो", "Long/Tall", "lamo", "Long"),
        ("छोटो", "Short", "chhoto", "Short"),
        ("सुन्दर", "Beautiful", "sundar", "Beautiful"),
        ("खुसी", "Happy", "khusi", "Happy"),
        ("दुखी", "Sad", "dukhi", "Sad"),
        ("थकित", "Tired", "thakit", "Tired"),
        ("बिरामी", "Sick", "birami", "Sick"),
        ("स्वस्थ", "Healthy", "swastha", "Healthy"),
        ("सफा", "Clean", "sapha", "Clean"),
    ],
    "places": [
        ("घर", "House", "ghar", "House"),
        ("विद्यालय", "School", "vidyalaya", "School"),
        ("बजार", "Market", "bazaar", "Market"),
        ("अस्पताल", "Hospital", "aspatal", "Hospital"),
        ("मन्दिर", "Temple", "mandir", "Temple"),
        ("बैंक", "Bank", "bank", "Bank"),
        ("पसल", "Shop", "pasal", "Shop"),
        ("होटल", "Hotel", "hotel", "Hotel"),
        ("कार्यालय", "Office", "karyalaya", "Office"),
        ("विमानस्थल", "Airport", "bimansthal", "Airport"),
        ("बस पार्क", "Bus station", "bus park", "Bus station"),
        ("पुस्तकालय", "Library", "pustakalaya", "Library"),
        ("चिडियाखाना", "Zoo", "chidiyakhana", "Zoo"),
        ("पार्क", "Park", "park", "Park"),
        ("रेस्टुरेन्ट", "Restaurant", "restaurant", "Restaurant"),
    ],
}

ELEMENTARY_VOCAB = {
    "travel": [
        ("यात्रा", "Travel", "yatra", "Journey"),
        ("बस", "Bus", "bus", "Bus"),
        ("गाडी", "Car", "gadi", "Vehicle"),
        ("टिकट", "Ticket", "tikat", "Ticket"),
        ("स्टेशन", "Station", "station", "Station"),
        ("सडक", "Road", "sadak", "Road"),
        ("बाटो", "Way/Path", "bato", "Way"),
        ("नक्सा", "Map", "naksha", "Map"),
        ("कोठा", "Room", "kotha", "Room"),
        ("सामान", "Luggage", "saman", "Luggage"),
        ("झोला", "Bag", "jhola", "Bag"),
        ("पासपोर्ट", "Passport", "passport", "Passport"),
        ("भिसा", "Visa", "visa", "Visa"),
        ("विमान", "Airplane", "biman", "Airplane"),
        ("रेल", "Train", "rel", "Train"),
        ("साइकल", "Bicycle", "cycle", "Bicycle"),
        ("मोटरसाइकल", "Motorcycle", "motorcycle", "Motorcycle"),
        ("ट्याक्सी", "Taxi", "taxi", "Taxi"),
        ("रिक्सा", "Rickshaw", "riksa", "Rickshaw"),
        ("पुल", "Bridge", "pul", "Bridge"),
    ],
    "time": [
        ("समय", "Time", "samaya", "Time"),
        ("घण्टा", "Hour", "ghanta", "Hour"),
        ("मिनेट", "Minute", "minet", "Minute"),
        ("सेकेन्ड", "Second", "second", "Second"),
        ("बिहान", "Morning", "bihan", "Morning"),
        ("दिउँसो", "Afternoon", "diunso", "Afternoon"),
        ("साँझ", "Evening", "sanjh", "Evening"),
        ("रात", "Night", "raat", "Night"),
        ("आज", "Today", "aaja", "Today"),
        ("भोलि", "Tomorrow", "bholi", "Tomorrow"),
        ("हिजो", "Yesterday", "hijo", "Yesterday"),
        ("परसि", "Day after tomorrow", "parsi", "Day after"),
        ("अस्ति", "Day before yesterday", "asti", "Day before"),
        ("हप्ता", "Week", "hapta", "Week"),
        ("महिना", "Month", "mahina", "Month"),
        ("वर्ष", "Year", "barsha", "Year"),
        ("ढिलो", "Late", "dhilo", "Late"),
        ("छिटो", "Fast/Early", "chhito", "Fast"),
        ("अहिले", "Now", "ahile", "Now"),
        ("पछि", "Later", "pachhi", "Later"),
    ],
    "animals": [
        ("कुकुर", "Dog", "kukur", "Dog"),
        ("बिरालो", "Cat", "biralo", "Cat"),
        ("गाई", "Cow", "gai", "Cow"),
        ("भैंसी", "Buffalo", "bhainsi", "Buffalo"),
        ("बाख्रा", "Goat", "bakhra", "Goat"),
        ("भेडा", "Sheep", "bheda", "Sheep"),
        ("घोडा", "Horse", "ghoda", "Horse"),
        ("हात्ती", "Elephant", "hatti", "Elephant"),
        ("बाघ", "Tiger", "bagh", "Tiger"),
        ("सिंह", "Lion", "singha", "Lion"),
        ("बाँदर", "Monkey", "bandar", "Monkey"),
        ("खरायो", "Rabbit", "kharayo", "Rabbit"),
        ("मुसो", "Mouse", "muso", "Mouse"),
        ("सुँगुर", "Pig", "sungur", "Pig"),
        ("कुखुरा", "Chicken", "kukhura", "Chicken"),
        ("हाँस", "Duck", "hans", "Duck"),
        ("चरा", "Bird", "chara", "Bird"),
        ("माछा", "Fish", "machha", "Fish"),
        ("साँप", "Snake", "sanp", "Snake"),
        ("मौरी", "Bee", "mauri", "Bee"),
    ],
    "weather": [
        ("मौसम", "Weather", "mausam", "Weather"),
        ("घाम", "Sun/Sunshine", "gham", "Sun"),
        ("पानी पर्यो", "It rained", "pani paryo", "Rain"),
        ("हिउँ", "Snow", "hiun", "Snow"),
        ("बादल", "Cloud", "badal", "Cloud"),
        ("हावा", "Wind", "hawa", "Wind"),
        ("गर्मी", "Heat/Summer", "garmi", "Hot"),
        ("जाडो", "Winter/Cold", "jado", "Cold"),
        ("वर्षा", "Rain/Monsoon", "barsha", "Rain"),
        ("बाढी", "Flood", "badhi", "Flood"),
        ("भूकम्प", "Earthquake", "bhukampa", "Earthquake"),
        ("पहिरो", "Landslide", "pahiro", "Landslide"),
        ("कुहिरो", "Fog", "kuhiro", "Fog"),
        ("तुषारो", "Frost", "tusaro", "Frost"),
        ("इन्द्रेणी", "Rainbow", "indreni", "Rainbow"),
        ("आँधी", "Storm", "aadhi", "Storm"),
        ("बिजुली", "Lightning", "bijuli", "Lightning"),
        ("गर्जन", "Thunder", "garjan", "Thunder"),
        ("ओसिलो", "Humid", "osilo", "Humid"),
        ("सुक्खा", "Dry", "sukkha", "Dry"),
    ],
    "emotions": [
        ("खुसी", "Happy", "khusi", "Happy"),
        ("दुखी", "Sad", "dukhi", "Sad"),
        ("रिसाएको", "Angry", "risaeko", "Angry"),
        ("डराएको", "Scared", "daraeko", "Scared"),
        ("थकित", "Tired", "thakit", "Tired"),
        ("उत्साहित", "Excited", "utsahit", "Excited"),
        ("चिन्तित", "Worried", "chintit", "Worried"),
        ("आश्चर्यचकित", "Surprised", "ascharyachakit", "Surprised"),
        ("निराश", "Disappointed", "nirash", "Disappointed"),
        ("संतुष्ट", "Satisfied", "santusht", "Satisfied"),
        ("प्रेम", "Love", "prem", "Love"),
        ("माया", "Affection", "maya", "Affection"),
        ("घृणा", "Hatred", "ghrina", "Hatred"),
        ("ईर्ष्या", "Jealousy", "irshya", "Jealousy"),
        ("गर्व", "Pride", "garba", "Pride"),
        ("लाज", "Shame/Shy", "laaj", "Shame"),
        ("एक्लो", "Lonely", "eklo", "Lonely"),
        ("शान्त", "Calm", "shanta", "Calm"),
        ("तनाव", "Stress", "tanav", "Stress"),
        ("आनन्द", "Joy", "ananda", "Joy"),
    ],
    "shopping": [
        ("पैसा", "Money", "paisa", "Money"),
        ("रुपैयाँ", "Rupees", "rupaiya", "Rupees"),
        ("मूल्य", "Price", "mulya", "Price"),
        ("छुट", "Discount", "chhut", "Discount"),
        ("कपडा", "Clothes", "kapda", "Clothes"),
        ("जुत्ता", "Shoes", "jutta", "Shoes"),
        ("टोपी", "Hat", "topi", "Hat"),
        ("साडी", "Sari", "sadi", "Sari"),
        ("कुर्ता", "Kurta", "kurta", "Kurta"),
        ("पाइन्ट", "Pants", "paint", "Pants"),
        ("सर्ट", "Shirt", "shirt", "Shirt"),
        ("चप्पल", "Slippers", "chappal", "Slippers"),
        ("मोजा", "Socks", "moja", "Socks"),
        ("बेल्ट", "Belt", "belt", "Belt"),
        ("घडी", "Watch", "ghadi", "Watch"),
        ("चस्मा", "Glasses", "chasma", "Glasses"),
        ("छाता", "Umbrella", "chhata", "Umbrella"),
        ("पर्स", "Wallet/Purse", "purse", "Wallet"),
        ("गहना", "Jewelry", "gahana", "Jewelry"),
        ("औंठी", "Ring", "authi", "Ring"),
    ],
}

INTERMEDIATE_VOCAB = {
    "work": [
        ("काम", "Work", "kaam", "Work"),
        ("नौकरी", "Job", "naukari", "Job"),
        ("कार्यालय", "Office", "karyalaya", "Office"),
        ("मालिक", "Boss", "malik", "Boss"),
        ("कर्मचारी", "Employee", "karmachari", "Employee"),
        ("तलब", "Salary", "talab", "Salary"),
        ("बैठक", "Meeting", "baithak", "Meeting"),
        ("परियोजना", "Project", "pariyojana", "Project"),
        ("समयसीमा", "Deadline", "samaysima", "Deadline"),
        ("इमेल", "Email", "email", "Email"),
        ("कम्प्युटर", "Computer", "computer", "Computer"),
        ("फोन", "Phone", "phone", "Phone"),
        ("रिपोर्ट", "Report", "report", "Report"),
        ("अन्तर्वार्ता", "Interview", "antarwarta", "Interview"),
        ("आवेदन", "Application", "awedan", "Application"),
        ("अनुभव", "Experience", "anubhav", "Experience"),
        ("योग्यता", "Qualification", "yogyata", "Qualification"),
        ("पदोन्नति", "Promotion", "padonnati", "Promotion"),
        ("छुट्टी", "Leave", "chhuti", "Leave"),
        ("कर्तव्य", "Duty", "kartabya", "Duty"),
    ],
    "education": [
        ("शिक्षा", "Education", "shiksha", "Education"),
        ("विश्वविद्यालय", "University", "bishwavidyalaya", "University"),
        ("कक्षा", "Class", "kaksha", "Class"),
        ("शिक्षक", "Teacher", "shikshak", "Teacher"),
        ("विद्यार्थी", "Student", "vidyarthi", "Student"),
        ("किताब", "Book", "kitab", "Book"),
        ("कापी", "Notebook", "kapi", "Notebook"),
        ("कलम", "Pen", "kalam", "Pen"),
        ("परीक्षा", "Exam", "pariksha", "Exam"),
        ("उत्तीर्ण", "Pass", "uttirna", "Pass"),
        ("अनुत्तीर्ण", "Fail", "anuttirna", "Fail"),
        ("अंक", "Marks", "anka", "Marks"),
        ("प्रमाणपत्र", "Certificate", "pramanpatra", "Certificate"),
        ("डिग्री", "Degree", "degree", "Degree"),
        ("विषय", "Subject", "bishaya", "Subject"),
        ("गणित", "Mathematics", "ganit", "Math"),
        ("विज्ञान", "Science", "bigyan", "Science"),
        ("इतिहास", "History", "itihas", "History"),
        ("भूगोल", "Geography", "bhugol", "Geography"),
        ("अंग्रेजी", "English", "angreji", "English"),
    ],
    "health": [
        ("स्वास्थ्य", "Health", "swasthya", "Health"),
        ("बिरामी", "Patient", "birami", "Patient"),
        ("डाक्टर", "Doctor", "doctor", "Doctor"),
        ("नर्स", "Nurse", "nurse", "Nurse"),
        ("औषधि", "Medicine", "ausadhi", "Medicine"),
        ("टाउको दुख्यो", "Headache", "tauko dukhyo", "Headache"),
        ("पेट दुख्यो", "Stomachache", "pet dukhyo", "Stomachache"),
        ("रुघा", "Cold", "rugha", "Cold"),
        ("ज्वरो", "Fever", "jwaro", "Fever"),
        ("खोकी", "Cough", "khoki", "Cough"),
        ("चोट", "Injury", "chot", "Injury"),
        ("रगत", "Blood", "ragat", "Blood"),
        ("इन्जेक्सन", "Injection", "injection", "Injection"),
        ("अपरेशन", "Operation", "operation", "Operation"),
        ("एलर्जी", "Allergy", "allergy", "Allergy"),
        ("मधुमेह", "Diabetes", "madhumeh", "Diabetes"),
        ("रक्तचाप", "Blood pressure", "raktachap", "BP"),
        ("हृदय", "Heart", "hridaya", "Heart"),
        ("फोक्सो", "Lungs", "phokso", "Lungs"),
        ("मिर्गौला", "Kidney", "mirgaula", "Kidney"),
    ],
    "culture": [
        ("संस्कृति", "Culture", "sanskriti", "Culture"),
        ("परम्परा", "Tradition", "parampara", "Tradition"),
        ("चाडपर्व", "Festival", "chadparva", "Festival"),
        ("दशैं", "Dashain", "dashain", "Dashain"),
        ("तिहार", "Tihar", "tihar", "Tihar"),
        ("होली", "Holi", "holi", "Holi"),
        ("पूजा", "Worship", "puja", "Worship"),
        ("गुम्बा", "Monastery", "gumba", "Monastery"),
        ("भगवान", "God", "bhagwan", "God"),
        ("प्रार्थना", "Prayer", "prarthana", "Prayer"),
        ("दीप", "Lamp", "dip", "Lamp"),
        ("टीका", "Tika", "tika", "Tika"),
        ("जमरा", "Jamara", "jamara", "Jamara"),
        ("देउसी", "Deusi", "deusi", "Tihar song"),
        ("भैलो", "Bhailo", "bhailo", "Tihar song"),
        ("रङ्गोली", "Rangoli", "rangoli", "Floor art"),
        ("आरती", "Aarti", "aarti", "Ritual"),
        ("प्रसाद", "Prasad", "prasad", "Offering"),
        ("मन्त्र", "Mantra", "mantra", "Chant"),
        ("ध्यान", "Meditation", "dhyan", "Meditation"),
    ],
    "nature": [
        ("प्रकृति", "Nature", "prakriti", "Nature"),
        ("हिमाल", "Mountain", "himal", "Mountain"),
        ("पहाड", "Hill", "pahad", "Hill"),
        ("खोला", "Stream", "khola", "Stream"),
        ("नदी", "River", "nadi", "River"),
        ("ताल", "Lake", "taal", "Lake"),
        ("समुद्र", "Sea", "samudra", "Sea"),
        ("जंगल", "Forest", "jangal", "Forest"),
        ("रुख", "Tree", "rukh", "Tree"),
        ("फूल", "Flower", "phul", "Flower"),
        ("घाँस", "Grass", "ghas", "Grass"),
        ("पात", "Leaf", "paat", "Leaf"),
        ("जरा", "Root", "jara", "Root"),
        ("हाँगा", "Branch", "hanga", "Branch"),
        ("चट्टान", "Rock", "chattan", "Rock"),
        ("माटो", "Soil", "mato", "Soil"),
        ("बालुवा", "Sand", "baluwa", "Sand"),
        ("झरना", "Waterfall", "jharna", "Waterfall"),
        ("गुफा", "Cave", "gupha", "Cave"),
        ("उपत्यका", "Valley", "upatyaka", "Valley"),
    ],
}

ADVANCED_VOCAB = {
    "politics": [
        ("राजनीति", "Politics", "rajniti", "Politics"),
        ("सरकार", "Government", "sarkar", "Government"),
        ("संसद", "Parliament", "sansad", "Parliament"),
        ("प्रधानमन्त्री", "Prime Minister", "pradhanmantri", "PM"),
        ("राष्ट्रपति", "President", "rashtrapati", "President"),
        ("मन्त्री", "Minister", "mantri", "Minister"),
        ("चुनाव", "Election", "chunav", "Election"),
        ("मतदान", "Voting", "matdan", "Voting"),
        ("पार्टी", "Party", "party", "Party"),
        ("संविधान", "Constitution", "sambidhan", "Constitution"),
        ("कानून", "Law", "kanun", "Law"),
        ("अदालत", "Court", "adalat", "Court"),
        ("न्याय", "Justice", "nyaya", "Justice"),
        ("अधिकार", "Rights", "adhikar", "Rights"),
        ("स्वतन्त्रता", "Freedom", "swatantrata", "Freedom"),
        ("प्रजातन्त्र", "Democracy", "prajatantra", "Democracy"),
        ("राजतन्त्र", "Monarchy", "rajtantra", "Monarchy"),
        ("नीति", "Policy", "niti", "Policy"),
        ("विधेयक", "Bill", "bidheyak", "Bill"),
        ("संधि", "Treaty", "sandhi", "Treaty"),
        ("राजदूत", "Ambassador", "rajdut", "Ambassador"),
        ("मतदाता", "Voter", "matdata", "Voter"),
        ("उम्मेदवार", "Candidate", "ummedwar", "Candidate"),
        ("विपक्ष", "Opposition", "bipaksha", "Opposition"),
        ("सत्तारूढ", "Ruling", "sattarudh", "Ruling"),
    ],
    "environment": [
        ("वातावरण", "Environment", "watawaran", "Environment"),
        ("प्रदूषण", "Pollution", "pradushan", "Pollution"),
        ("जलवायु", "Climate", "jalwayu", "Climate"),
        ("परिवर्तन", "Change", "pariwartan", "Change"),
        ("संरक्षण", "Conservation", "sanrakshan", "Conservation"),
        ("जैविक", "Organic", "jaiwik", "Organic"),
        ("पुनर्नवीकरण", "Recycling", "punarnawikaran", "Recycling"),
        ("कार्बन", "Carbon", "carbon", "Carbon"),
        ("उत्सर्जन", "Emission", "utsarjan", "Emission"),
        ("जैवविविधता", "Biodiversity", "jaiwabibiddhata", "Biodiversity"),
        ("वनजंगल", "Forest", "wanjangal", "Forest"),
        ("वन्यजन्तु", "Wildlife", "wanyajantu", "Wildlife"),
        ("संकटापन्न", "Endangered", "sankatapanna", "Endangered"),
        ("प्राकृतिक", "Natural", "prakritik", "Natural"),
        ("हरितगृह", "Greenhouse", "haritgriha", "Greenhouse"),
    ],
    "economics": [
        ("अर्थतन्त्र", "Economy", "arthatantra", "Economy"),
        ("बजेट", "Budget", "bajet", "Budget"),
        ("कर", "Tax", "kar", "Tax"),
        ("ऋण", "Loan", "rin", "Loan"),
        ("बचत", "Savings", "bachat", "Savings"),
        ("लगानी", "Investment", "lagani", "Investment"),
        ("मुद्रास्फीति", "Inflation", "mudrasphiti", "Inflation"),
        ("बेरोजगारी", "Unemployment", "berojgari", "Unemployment"),
        ("व्यापार", "Trade", "byapar", "Trade"),
        ("निर्यात", "Export", "niryat", "Export"),
        ("आयात", "Import", "aayat", "Import"),
        ("शेयर", "Share", "share", "Stock"),
        ("मुनाफा", "Profit", "munafa", "Profit"),
        ("घाटा", "Loss", "ghata", "Loss"),
        ("पूँजी", "Capital", "puji", "Capital"),
        ("ब्याज", "Interest", "byaj", "Interest"),
        ("विनिमय दर", "Exchange rate", "binimaya dar", "Rate"),
        ("गरिबी", "Poverty", "garibi", "Poverty"),
        ("विकास", "Development", "bikas", "Development"),
        ("उत्पादन", "Production", "utpadan", "Production"),
    ],
    "technology": [
        ("प्रविधि", "Technology", "prabidhi", "Tech"),
        ("इन्टरनेट", "Internet", "internet", "Internet"),
        ("सफ्टवेयर", "Software", "software", "Software"),
        ("हार्डवेयर", "Hardware", "hardware", "Hardware"),
        ("एप्लिकेसन", "Application", "application", "App"),
        ("वेबसाइट", "Website", "website", "Website"),
        ("डाटा", "Data", "data", "Data"),
        ("सर्भर", "Server", "server", "Server"),
        ("क्लाउड", "Cloud", "cloud", "Cloud"),
        ("पासवर्ड", "Password", "password", "Password"),
        ("कृत्रिम बुद्धिमत्ता", "AI", "kritrim buddhimatta", "AI"),
        ("रोबोट", "Robot", "robot", "Robot"),
        ("नेटवर्क", "Network", "network", "Network"),
        ("भाइरस", "Virus", "virus", "Virus"),
        ("ब्याकअप", "Backup", "backup", "Backup"),
        ("डाउनलोड", "Download", "download", "Download"),
        ("अपलोड", "Upload", "upload", "Upload"),
        ("प्रिन्ट", "Print", "print", "Print"),
        ("स्क्यान", "Scan", "scan", "Scan"),
        ("सर्च", "Search", "search", "Search"),
    ],
    "media": [
        ("सञ्चार", "Communication", "sanchar", "Media"),
        ("समाचार", "News", "samachar", "News"),
        ("पत्रिका", "Newspaper", "patrika", "Newspaper"),
        ("रेडियो", "Radio", "radio", "Radio"),
        ("टेलिभिजन", "Television", "television", "TV"),
        ("सामाजिक सञ्जाल", "Social media", "samajik sanjal", "Social"),
        ("विज्ञापन", "Advertisement", "bigyapan", "Ad"),
        ("पत्रकार", "Journalist", "patrakar", "Journalist"),
        ("सम्पादक", "Editor", "sampadak", "Editor"),
        ("प्रकाशन", "Publication", "prakashan", "Publication"),
        ("प्रसारण", "Broadcast", "prasaran", "Broadcast"),
        ("अन्तर्वार्ता", "Interview", "antarwarta", "Interview"),
        ("भिडियो", "Video", "video", "Video"),
        ("अडियो", "Audio", "audio", "Audio"),
        ("फोटो", "Photo", "photo", "Photo"),
        ("क्यामेरा", "Camera", "camera", "Camera"),
        ("माइक्रोफोन", "Microphone", "microphone", "Mic"),
        ("स्टुडियो", "Studio", "studio", "Studio"),
        ("च्यानल", "Channel", "channel", "Channel"),
        ("कार्यक्रम", "Program", "karyakram", "Program"),
    ],
}

PROFICIENT_VOCAB = {
    "literature": [
        ("साहित्य", "Literature", "sahitya", "Literature"),
        ("कविता", "Poetry", "kavita", "Poetry"),
        ("कथा", "Story", "katha", "Story"),
        ("उपन्यास", "Novel", "upanyas", "Novel"),
        ("नाटक", "Drama", "natak", "Drama"),
        ("निबन्ध", "Essay", "nibandha", "Essay"),
        ("लेखक", "Writer", "lekhak", "Writer"),
        ("कवि", "Poet", "kavi", "Poet"),
        ("समीक्षा", "Criticism", "samiksha", "Review"),
        ("पात्र", "Character", "patra", "Character"),
        ("कथानक", "Plot", "kathanak", "Plot"),
        ("शैली", "Style", "shaili", "Style"),
        ("रूपक", "Metaphor", "rupak", "Metaphor"),
        ("उपमा", "Simile", "upama", "Simile"),
        ("व्यंग्य", "Satire", "byangya", "Satire"),
        ("गीत", "Song/Lyric", "git", "Song"),
        ("गजल", "Ghazal", "gajal", "Ghazal"),
        ("महाकाव्य", "Epic", "mahakavya", "Epic"),
        ("छन्द", "Verse/Meter", "chhanda", "Verse"),
        ("अलंकार", "Figure of speech", "alankar", "Ornament"),
        ("पद्य", "Verse", "padya", "Verse"),
        ("गद्य", "Prose", "gadya", "Prose"),
        ("संवाद", "Dialogue", "samwad", "Dialogue"),
        ("वर्णन", "Description", "warnan", "Description"),
        ("भावना", "Emotion", "bhawana", "Emotion"),
    ],
    "philosophy": [
        ("दर्शन", "Philosophy", "darshan", "Philosophy"),
        ("ज्ञान", "Knowledge", "gyan", "Knowledge"),
        ("सत्य", "Truth", "satya", "Truth"),
        ("धर्म", "Religion/Duty", "dharma", "Dharma"),
        ("कर्म", "Action", "karma", "Karma"),
        ("मोक्ष", "Liberation", "moksha", "Liberation"),
        ("आत्मा", "Soul", "aatma", "Soul"),
        ("ब्रह्म", "Supreme Being", "brahma", "Brahma"),
        ("माया", "Illusion", "maya", "Maya"),
        ("योग", "Yoga", "yoga", "Yoga"),
        ("शान्ति", "Peace", "shanti", "Peace"),
        ("अहिंसा", "Non-violence", "ahinsa", "Ahimsa"),
        ("करुणा", "Compassion", "karuna", "Compassion"),
        ("बोधि", "Enlightenment", "bodhi", "Bodhi"),
        ("निर्वाण", "Nirvana", "nirvan", "Nirvana"),
        ("चेतना", "Consciousness", "chetana", "Awareness"),
        ("अस्तित्व", "Existence", "astitwa", "Existence"),
        ("तर्क", "Logic", "tarka", "Logic"),
        ("नैतिकता", "Ethics", "naitikta", "Ethics"),
        ("आध्यात्मिक", "Spiritual", "adhyatmik", "Spiritual"),
        ("विवेक", "Wisdom", "bibek", "Wisdom"),
        ("ध्यान", "Meditation", "dhyan", "Meditation"),
        ("समाधि", "Concentration", "samadhi", "Samadhi"),
        ("संन्यास", "Renunciation", "sannyas", "Renunciation"),
        ("मुक्ति", "Freedom", "mukti", "Freedom"),
    ],
    "law": [
        ("न्याय", "Justice", "nyaya", "Justice"),
        ("अधिकार", "Rights", "adhikar", "Rights"),
        ("कर्तव्य", "Duty", "kartabya", "Duty"),
        ("अदालत", "Court", "adalat", "Court"),
        ("न्यायाधीश", "Judge", "nyayadhish", "Judge"),
        ("वकिल", "Lawyer", "wakil", "Lawyer"),
        ("मुद्दा", "Case", "mudda", "Case"),
        ("प्रमाण", "Evidence", "praman", "Evidence"),
        ("साक्षी", "Witness", "sakshi", "Witness"),
        ("अभियोग", "Prosecution", "abhiyog", "Prosecution"),
        ("प्रतिवादी", "Defendant", "pratiwadi", "Defendant"),
        ("फैसला", "Verdict", "phaisala", "Verdict"),
        ("सजाय", "Punishment", "sajay", "Punishment"),
        ("जरिवाना", "Fine", "jariwana", "Fine"),
        ("कैद", "Imprisonment", "kaid", "Prison"),
        ("अपील", "Appeal", "apil", "Appeal"),
        ("जमानत", "Bail", "jamanat", "Bail"),
        ("गिरफ्तारी", "Arrest", "giraftari", "Arrest"),
        ("अपराध", "Crime", "aparadh", "Crime"),
        ("दण्ड", "Penalty", "danda", "Penalty"),
        ("वादी", "Plaintiff", "wadi", "Plaintiff"),
        ("ऐन", "Act", "ain", "Act"),
        ("नियम", "Rule", "niyam", "Rule"),
        ("विनियम", "Regulation", "biniyam", "Regulation"),
        ("निर्देशिका", "Directive", "nirdeshika", "Directive"),
    ],
    "academics": [
        ("अनुसन्धान", "Research", "anusandhan", "Research"),
        ("प्रकाशन", "Publication", "prakashan", "Publication"),
        ("सिद्धान्त", "Theory", "siddhanta", "Theory"),
        ("अवधारणा", "Concept", "awadharana", "Concept"),
        ("विश्लेषण", "Analysis", "bishleshan", "Analysis"),
        ("संश्लेषण", "Synthesis", "sanshleshan", "Synthesis"),
        ("मूल्यांकन", "Evaluation", "mulyankan", "Evaluation"),
        ("निष्कर्ष", "Conclusion", "nishkarsha", "Conclusion"),
        ("परिकल्पना", "Hypothesis", "parikalpana", "Hypothesis"),
        ("प्रयोग", "Experiment", "prayog", "Experiment"),
        ("प्रमेय", "Theorem", "prameya", "Theorem"),
        ("तथ्य", "Fact", "tathya", "Fact"),
        ("सन्दर्भ", "Reference", "sandarbha", "Reference"),
        ("उद्धरण", "Citation", "uddharan", "Citation"),
        ("ग्रन्थ", "Thesis", "grantha", "Thesis"),
    ],
}

def create_flashcard(level_prefix, word, meaning, roman, desc, level, category, idx):
    return {
        "id": f"{level_prefix}_{category}_{idx:03d}",
        "front": word,
        "back": meaning,
        "romanization": roman,
        "meaning": desc,
        "level": level,
        "category": category,
        "examples": [word],
        "isFavorite": False,
        "reviewCount": 0,
        "correctCount": 0
    }

def generate_level_flashcards(level, vocab_dict, prefix):
    flashcards = []
    idx = 1
    for category, words in vocab_dict.items():
        for word, meaning, roman, desc in words:
            flashcards.append(create_flashcard(prefix, word, meaning, roman, desc, level, category, idx))
            idx += 1
    return flashcards

def generate_all_flashcards():
    all_data = {
        "beginner": generate_level_flashcards("Beginner", BEGINNER_VOCAB, "b"),
        "elementary": generate_level_flashcards("Elementary", ELEMENTARY_VOCAB, "e"),
        "intermediate": generate_level_flashcards("Intermediate", INTERMEDIATE_VOCAB, "i"),
        "advanced": generate_level_flashcards("Advanced", ADVANCED_VOCAB, "a"),
        "proficient": generate_level_flashcards("Proficient", PROFICIENT_VOCAB, "p"),
    }
    return all_data

if __name__ == "__main__":
    print("🇳🇵 Generating Flashcards...")
    data = generate_all_flashcards()
    for level, cards in data.items():
        print(f"  {level}: {len(cards)} flashcards")

